const HOME_KEYS = ['KeyA', 'KeyS', 'KeyD', 'KeyF', 'KeyJ', 'KeyK', 'KeyL', 'Semicolon']
const SPACE_KEY = ['Space']

const TOP_NEAR_LEFT = ['KeyE', 'KeyR', 'KeyT']
const TOP_NEAR_RIGHT = ['KeyY', 'KeyU', 'KeyI']
const TOP_NEAR = [...TOP_NEAR_LEFT, ...TOP_NEAR_RIGHT]

const BOTTOM_NEAR_LEFT = ['KeyC', 'KeyV', 'KeyB']
const BOTTOM_NEAR_RIGHT = ['KeyN', 'KeyM', 'Comma']
const BOTTOM_NEAR = [...BOTTOM_NEAR_LEFT, ...BOTTOM_NEAR_RIGHT]

const LEFT_PINKY_KEYS = ['KeyQ', 'KeyA', 'KeyZ']
const RIGHT_PINKY_KEYS = ['KeyP', 'Semicolon', 'Slash']

const LEFT_INDEX_ZONE = ['KeyR', 'KeyT', 'KeyF', 'KeyG', 'KeyV', 'KeyB']
const RIGHT_INDEX_ZONE = ['KeyY', 'KeyU', 'KeyH', 'KeyJ', 'KeyN', 'KeyM']

const FULL_ALPHA_KEYS = [
    'KeyQ', 'KeyW', 'KeyE', 'KeyR', 'KeyT',
    'KeyA', 'KeyS', 'KeyD', 'KeyF', 'KeyG',
    'KeyY', 'KeyU', 'KeyI', 'KeyO', 'KeyP',
    'KeyH', 'KeyJ', 'KeyK', 'KeyL', 'Semicolon',
    'KeyZ', 'KeyX', 'KeyC', 'KeyV', 'KeyB',
    'KeyN', 'KeyM', 'Comma', 'Period', 'Slash',
]

const COPY_POWER_TARGET = {
    type: 'combo',
    codes: ['ControlLeft', 'KeyC'],
    triggerCode: 'KeyC',
    label: 'CTRL + C',
    shortLabel: 'CTRL+C',
    helper: 'Hold Ctrl, tap C',
    powerName: 'Copy Power',
}

const PASTE_POWER_TARGET = {
    type: 'combo',
    codes: ['ControlLeft', 'KeyV'],
    triggerCode: 'KeyV',
    label: 'CTRL + V',
    shortLabel: 'CTRL+V',
    helper: 'Hold Ctrl, tap V',
    powerName: 'Paste Power',
}

const UNDO_POWER_TARGET = {
    type: 'combo',
    codes: ['ControlLeft', 'KeyZ'],
    triggerCode: 'KeyZ',
    label: 'CTRL + Z',
    shortLabel: 'CTRL+Z',
    helper: 'Hold Ctrl, tap Z',
    powerName: 'Undo Power',
}

export const KEYBOARD_ROWS = [
    [
        { code: 'KeyQ', label: 'Q' },
        { code: 'KeyW', label: 'W' },
        { code: 'KeyE', label: 'E' },
        { code: 'KeyR', label: 'R' },
        { code: 'KeyT', label: 'T' },
        { code: 'KeyY', label: 'Y' },
        { code: 'KeyU', label: 'U' },
        { code: 'KeyI', label: 'I' },
        { code: 'KeyO', label: 'O' },
        { code: 'KeyP', label: 'P' },
    ],
    [
        { code: 'KeyA', label: 'A' },
        { code: 'KeyS', label: 'S' },
        { code: 'KeyD', label: 'D' },
        { code: 'KeyF', label: 'F' },
        { code: 'KeyG', label: 'G' },
        { code: 'KeyH', label: 'H' },
        { code: 'KeyJ', label: 'J' },
        { code: 'KeyK', label: 'K' },
        { code: 'KeyL', label: 'L' },
        { code: 'Semicolon', label: ';' },
    ],
    [
        { code: 'KeyZ', label: 'Z' },
        { code: 'KeyX', label: 'X' },
        { code: 'KeyC', label: 'C' },
        { code: 'KeyV', label: 'V' },
        { code: 'KeyB', label: 'B' },
        { code: 'KeyN', label: 'N' },
        { code: 'KeyM', label: 'M' },
        { code: 'Comma', label: ',' },
        { code: 'Period', label: '.' },
        { code: 'Slash', label: '/' },
    ],
    [
        { code: 'ControlLeft', label: 'CTRL' },
        { code: 'Space', label: 'SPACE', wide: true },
    ],
]

export const FINGER_COLORS = {
    lp: '#ff8a3d',
    lr: '#ffd84d',
    lm: '#54e3c2',
    li: '#58c7ff',
    ri: '#8f8cff',
    rm: '#c78cff',
    rr: '#ff8bc2',
    rp: '#ff7c93',
    th: '#5ee36d',
}

export const FINGER_LABELS = {
    lp: 'left pinky',
    lr: 'left ring',
    lm: 'left middle',
    li: 'left pointer',
    ri: 'right pointer',
    rm: 'right middle',
    rr: 'right ring',
    rp: 'right pinky',
    th: 'thumb',
}

export const KEY_TO_FINGER = {
    ControlLeft: 'lp',
    KeyQ: 'lp',
    KeyA: 'lp',
    KeyZ: 'lp',
    KeyW: 'lr',
    KeyS: 'lr',
    KeyX: 'lr',
    KeyE: 'lm',
    KeyD: 'lm',
    KeyC: 'lm',
    KeyR: 'li',
    KeyF: 'li',
    KeyV: 'li',
    KeyT: 'li',
    KeyG: 'li',
    KeyB: 'li',
    KeyY: 'ri',
    KeyH: 'ri',
    KeyN: 'ri',
    KeyU: 'ri',
    KeyJ: 'ri',
    KeyM: 'ri',
    KeyI: 'rm',
    KeyK: 'rm',
    Comma: 'rm',
    KeyO: 'rr',
    KeyL: 'rr',
    Period: 'rr',
    KeyP: 'rp',
    Semicolon: 'rp',
    Slash: 'rp',
    Space: 'th',
}

export const LEVELS = [
    {
        id: 'home-friends',
        world: 1,
        icon: '🏠',
        title: 'Home',
        challenge: 'Home row only',
        keys: [...HOME_KEYS],
        roundSize: 10,
    },
    {
        id: 'thumb-bounce',
        world: 1,
        icon: '👣',
        title: 'Thumb',
        challenge: 'Home row plus space',
        keys: [...HOME_KEYS, ...SPACE_KEY],
        roundSize: 12,
    },
    {
        id: 'tiny-reaches-up',
        world: 1,
        icon: '☁️',
        title: 'Up',
        challenge: 'Reach a little upward',
        keys: [...HOME_KEYS, ...TOP_NEAR],
        roundSize: 12,
    },
    {
        id: 'tiny-reaches-down',
        world: 1,
        icon: '🌱',
        title: 'Down',
        challenge: 'Reach a little downward',
        keys: [...HOME_KEYS, ...BOTTOM_NEAR],
        roundSize: 12,
    },
    {
        id: 'home-mix',
        world: 1,
        icon: '⭐',
        title: 'Mix',
        challenge: 'Home, up, down, and space together',
        keys: [...HOME_KEYS, ...TOP_NEAR, ...BOTTOM_NEAR, ...SPACE_KEY],
        roundSize: 14,
    },

    {
        id: 'pinky-power-left',
        world: 2,
        icon: '🧡',
        title: 'Left Pinky',
        challenge: 'Left pinky control',
        keys: [...LEFT_PINKY_KEYS, 'KeyS', 'KeyX', 'Space'],
        roundSize: 12,
    },
    {
        id: 'pinky-power-right',
        world: 2,
        icon: '💖',
        title: 'Right Pinky',
        challenge: 'Right pinky control',
        keys: [...RIGHT_PINKY_KEYS, 'KeyL', 'Period', 'Space'],
        roundSize: 12,
    },
    {
        id: 'pointer-patrol',
        world: 2,
        icon: '👉',
        title: 'Pointers',
        challenge: 'Busy index fingers',
        keys: [...LEFT_INDEX_ZONE, ...RIGHT_INDEX_ZONE, 'Space'],
        roundSize: 14,
    },
    {
        id: 'hand-bounce',
        world: 2,
        icon: '🎾',
        title: 'Bounce',
        challenge: 'Alternate left and right hands',
        keys: ['KeyA', 'KeyJ', 'KeyS', 'KeyK', 'KeyD', 'KeyL', 'KeyF', 'Semicolon', 'Space'],
        roundSize: 14,
    },
    {
        id: 'rainbow-mix',
        world: 2,
        icon: '🌈',
        title: 'Rainbow',
        challenge: 'All learned letters together',
        keys: [...FULL_ALPHA_KEYS, ...SPACE_KEY],
        roundSize: 16,
    },

    {
        id: 'word-sprouts',
        world: 3,
        icon: '🌼',
        title: 'Tiny Words',
        challenge: 'Read and type tiny words',
        keys: [...FULL_ALPHA_KEYS, ...SPACE_KEY],
        promptPool: ['cat', 'dog', 'sun', 'map', 'run', 'hat', 'jam', 'box'],
        promptCount: 5,
    },
    {
        id: 'space-builder',
        world: 3,
        icon: '🧱',
        title: 'Space Words',
        challenge: 'Type two-word phrases',
        keys: [...FULL_ALPHA_KEYS, ...SPACE_KEY],
        promptPool: ['red sun', 'big dog', 'fun run', 'hot jam', 'mad cat', 'run fast'],
        promptCount: 4,
    },
    {
        id: 'fast-fingers',
        world: 3,
        icon: '⚡',
        title: 'Fast Words',
        challenge: 'Type short real words faster',
        keys: [...FULL_ALPHA_KEYS, ...SPACE_KEY],
        promptPool: ['jump', 'rocket', 'planet', 'animal', 'yellow', 'window'],
        promptCount: 4,
    },
    {
        id: 'tricky-mix',
        world: 3,
        icon: '🌀',
        title: 'Tricky Words',
        challenge: 'Practice harder words and jumps',
        keys: [...FULL_ALPHA_KEYS, ...SPACE_KEY],
        promptPool: ['quick fox', 'puzzle box', 'vivid planet', 'jump high', 'magic rabbit'],
        promptCount: 4,
    },
    {
        id: 'story-trail',
        world: 3,
        icon: '📖',
        title: 'Story Time',
        challenge: 'Type short phrases and sentences',
        keys: [...FULL_ALPHA_KEYS, ...SPACE_KEY],
        promptPool: ['the cat can run', 'we jump in the sun', 'the rabbit is quick', 'you can do it', 'the dog is my pal'],
        promptCount: 3,
    },

    {
        id: 'copy-power',
        world: 4,
        icon: '📋',
        title: 'Copy',
        challenge: 'Learn Ctrl + C',
        power: 'copy',
        keys: ['ControlLeft', 'KeyC'],
        targets: [COPY_POWER_TARGET],
        roundSize: 1,
    },
    {
        id: 'paste-power',
        world: 4,
        icon: '📥',
        title: 'Paste',
        challenge: 'Learn Ctrl + V',
        power: 'paste',
        keys: ['ControlLeft', 'KeyV'],
        targets: [PASTE_POWER_TARGET],
        roundSize: 1,
    },
    {
        id: 'undo-power',
        world: 4,
        icon: '↩️',
        title: 'Undo',
        challenge: 'Learn Ctrl + Z',
        power: 'undo',
        keys: ['ControlLeft', 'KeyZ'],
        targets: [UNDO_POWER_TARGET],
        roundSize: 1,
    },
    {
        id: 'power-mix',
        world: 4,
        icon: '✨',
        title: 'Powers',
        challenge: 'Mix copy, paste, and undo',
        power: 'mix',
        keys: ['ControlLeft', 'KeyC', 'KeyV', 'KeyZ'],
        targets: [COPY_POWER_TARGET, PASTE_POWER_TARGET, UNDO_POWER_TARGET],
        roundSize: 12,
    },
    {
        id: 'super-keyboard-hero',
        world: 4,
        icon: '🏆',
        title: 'Hero',
        challenge: 'Typing and powers together',
        power: 'final',
        keys: [...FULL_ALPHA_KEYS, ...SPACE_KEY, 'ControlLeft'],
        targets: [
            { type: 'single', code: 'KeyF' },
            { type: 'single', code: 'KeyJ' },
            { type: 'single', code: 'Space' },
            COPY_POWER_TARGET,
            PASTE_POWER_TARGET,
            UNDO_POWER_TARGET,
        ],
        roundSize: 20,
    },

    {
        id: 'word-power-copy-paste',
        world: 5,
        icon: '📝',
        title: 'Word Copy',
        challenge: 'Copy and paste whole words',
        playMode: 'wordPowers',
        keys: ['ControlLeft', 'KeyC', 'KeyV'],
        missions: [
            {
                ...COPY_POWER_TARGET,
                taskLabel: 'Copy "cat"',
                sourceText: 'cat',
                clipboardText: '',
                targetText: '',
                successMessage: 'Copied "cat"!',
                afterState: { sourceText: 'cat', clipboardText: 'cat', targetText: '' },
            },
            {
                ...PASTE_POWER_TARGET,
                taskLabel: 'Paste "cat"',
                sourceText: 'cat',
                clipboardText: 'cat',
                targetText: '',
                successMessage: 'Pasted "cat"!',
                afterState: { sourceText: 'cat', clipboardText: 'cat', targetText: 'cat' },
            },
            {
                ...COPY_POWER_TARGET,
                taskLabel: 'Copy "sun"',
                sourceText: 'sun',
                clipboardText: 'cat',
                targetText: 'cat',
                successMessage: 'Copied "sun"!',
                afterState: { sourceText: 'sun', clipboardText: 'sun', targetText: 'cat' },
            },
            {
                ...PASTE_POWER_TARGET,
                taskLabel: 'Paste "sun"',
                sourceText: 'sun',
                clipboardText: 'sun',
                targetText: 'cat',
                successMessage: 'Pasted "sun"!',
                afterState: { sourceText: 'sun', clipboardText: 'sun', targetText: 'cat sun' },
            },
        ],
    },
    {
        id: 'word-power-letters',
        world: 5,
        icon: '🔤',
        title: 'Letters',
        challenge: 'Copy and paste characters',
        playMode: 'wordPowers',
        keys: ['ControlLeft', 'KeyC', 'KeyV'],
        missions: [
            {
                ...COPY_POWER_TARGET,
                taskLabel: 'Copy "A"',
                sourceText: 'A',
                clipboardText: '',
                targetText: '',
                successMessage: 'Copied "A"!',
                afterState: { sourceText: 'A', clipboardText: 'A', targetText: '' },
            },
            {
                ...PASTE_POWER_TARGET,
                taskLabel: 'Paste "A"',
                sourceText: 'A',
                clipboardText: 'A',
                targetText: '',
                successMessage: 'Pasted "A"!',
                afterState: { sourceText: 'A', clipboardText: 'A', targetText: 'A' },
            },
            {
                ...COPY_POWER_TARGET,
                taskLabel: 'Copy "T"',
                sourceText: 'T',
                clipboardText: 'A',
                targetText: 'A',
                successMessage: 'Copied "T"!',
                afterState: { sourceText: 'T', clipboardText: 'T', targetText: 'A' },
            },
            {
                ...PASTE_POWER_TARGET,
                taskLabel: 'Paste "T"',
                sourceText: 'T',
                clipboardText: 'T',
                targetText: 'A',
                successMessage: 'Pasted "T"!',
                afterState: { sourceText: 'T', clipboardText: 'T', targetText: 'AT' },
            },
        ],
    },
    {
        id: 'word-power-finish-word',
        world: 5,
        icon: '🧩',
        title: 'Finish Word',
        challenge: 'Use copy and paste to finish words',
        playMode: 'wordPowers',
        keys: ['ControlLeft', 'KeyC', 'KeyV'],
        missions: [
            {
                ...COPY_POWER_TARGET,
                taskLabel: 'Copy "t"',
                sourceText: 't',
                clipboardText: '',
                targetText: 'ca',
                successMessage: 'Copied "t"!',
                afterState: { sourceText: 't', clipboardText: 't', targetText: 'ca' },
            },
            {
                ...PASTE_POWER_TARGET,
                taskLabel: 'Paste to make "cat"',
                sourceText: 't',
                clipboardText: 't',
                targetText: 'ca',
                successMessage: 'Made "cat"!',
                afterState: { sourceText: 't', clipboardText: 't', targetText: 'cat' },
            },
            {
                ...COPY_POWER_TARGET,
                taskLabel: 'Copy "s"',
                sourceText: 's',
                clipboardText: 't',
                targetText: 'cat',
                successMessage: 'Copied "s"!',
                afterState: { sourceText: 's', clipboardText: 's', targetText: 'cat' },
            },
            {
                ...PASTE_POWER_TARGET,
                taskLabel: 'Paste to make "cats"',
                sourceText: 's',
                clipboardText: 's',
                targetText: 'cat',
                successMessage: 'Made "cats"!',
                afterState: { sourceText: 's', clipboardText: 's', targetText: 'cats' },
            },
        ],
    },
    {
        id: 'word-power-undo',
        world: 5,
        icon: '🛠️',
        title: 'Undo Fix',
        challenge: 'Fix mistakes with undo',
        playMode: 'wordPowers',
        keys: ['ControlLeft', 'KeyC', 'KeyV', 'KeyZ'],
        missions: [
            {
                ...COPY_POWER_TARGET,
                taskLabel: 'Copy "dog"',
                sourceText: 'dog',
                clipboardText: '',
                targetText: '',
                successMessage: 'Copied "dog"!',
                afterState: { sourceText: 'dog', clipboardText: 'dog', targetText: '' },
            },
            {
                ...PASTE_POWER_TARGET,
                taskLabel: 'Paste "dog"',
                sourceText: 'dog',
                clipboardText: 'dog',
                targetText: '',
                successMessage: 'Pasted "dog"!',
                afterState: { sourceText: 'dog', clipboardText: 'dog', targetText: 'dog' },
            },
            {
                ...UNDO_POWER_TARGET,
                taskLabel: 'Undo the mistake',
                sourceText: 'dog',
                clipboardText: 'dog',
                targetText: 'dog',
                successMessage: 'Undid it!',
                afterState: { sourceText: 'cat', clipboardText: 'dog', targetText: '' },
            },
            {
                ...COPY_POWER_TARGET,
                taskLabel: 'Copy "cat"',
                sourceText: 'cat',
                clipboardText: 'dog',
                targetText: '',
                successMessage: 'Copied "cat"!',
                afterState: { sourceText: 'cat', clipboardText: 'cat', targetText: '' },
            },
            {
                ...PASTE_POWER_TARGET,
                taskLabel: 'Paste "cat"',
                sourceText: 'cat',
                clipboardText: 'cat',
                targetText: '',
                successMessage: 'Fixed it!',
                afterState: { sourceText: 'cat', clipboardText: 'cat', targetText: 'cat' },
            },
        ],
    },
    {
        id: 'word-power-phrase-builder',
        world: 5,
        icon: '🏗️',
        title: 'Phrase Build',
        challenge: 'Build a whole phrase with word powers',
        playMode: 'wordPowers',
        keys: ['ControlLeft', 'KeyC', 'KeyV'],
        missions: [
            {
                ...COPY_POWER_TARGET,
                taskLabel: 'Copy "big"',
                sourceText: 'big',
                clipboardText: '',
                targetText: '',
                successMessage: 'Copied "big"!',
                afterState: { sourceText: 'big', clipboardText: 'big', targetText: '' },
            },
            {
                ...PASTE_POWER_TARGET,
                taskLabel: 'Paste "big"',
                sourceText: 'big',
                clipboardText: 'big',
                targetText: '',
                successMessage: 'Pasted "big"!',
                afterState: { sourceText: 'big', clipboardText: 'big', targetText: 'big' },
            },
            {
                ...COPY_POWER_TARGET,
                taskLabel: 'Copy "red"',
                sourceText: 'red',
                clipboardText: 'big',
                targetText: 'big',
                successMessage: 'Copied "red"!',
                afterState: { sourceText: 'red', clipboardText: 'red', targetText: 'big' },
            },
            {
                ...PASTE_POWER_TARGET,
                taskLabel: 'Paste "red"',
                sourceText: 'red',
                clipboardText: 'red',
                targetText: 'big',
                successMessage: 'Pasted "red"!',
                afterState: { sourceText: 'red', clipboardText: 'red', targetText: 'big red' },
            },
            {
                ...COPY_POWER_TARGET,
                taskLabel: 'Copy "dog"',
                sourceText: 'dog',
                clipboardText: 'red',
                targetText: 'big red',
                successMessage: 'Copied "dog"!',
                afterState: { sourceText: 'dog', clipboardText: 'dog', targetText: 'big red' },
            },
            {
                ...PASTE_POWER_TARGET,
                taskLabel: 'Paste "dog"',
                sourceText: 'dog',
                clipboardText: 'dog',
                targetText: 'big red',
                successMessage: 'Built the phrase!',
                afterState: { sourceText: 'dog', clipboardText: 'dog', targetText: 'big red dog' },
            },
        ],
    },
]

export const codeToLabel = Object.fromEntries(
    KEYBOARD_ROWS.flat().map((key) => [key.code, key.label]),
)